const K='dfv-v2',seed={orders:[],appointments:[],invoices:[],items:[],cash:[],employees:[],recipes:[]};let db=JSON.parse(localStorage.getItem(K)||'null')||seed;
const $=s=>document.querySelector(s), euro=n=>new Intl.NumberFormat('de-DE',{style:'currency',currency:'EUR'}).format(Number(n)||0), esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m])),uid=()=>Date.now()+Math.random().toString(16).slice(2),save=()=>{localStorage.setItem(K,JSON.stringify(db));render()};
function del(t,id){db[t]=db[t].filter(x=>x.id!==id);save()}function empty(n,t){return '<tr><td colspan="'+n+'" class="muted">'+t+'</td></tr>'}
function render(){ $('#statOrders').textContent=db.orders.filter(x=>x.status!=='Erledigt').length;$('#statAppointments').textContent=db.appointments.length;$('#statInvoices').textContent=db.invoices.filter(x=>x.status!=='Bezahlt').length;$('#statStock').textContent=db.items.reduce((a,x)=>a+(+x.stock||0),0);
$('#ordersBody').innerHTML=db.orders.map(x=>'<tr><td>'+esc(x.customer)+'</td><td>'+esc(x.order)+'</td><td>'+esc(x.date)+'</td><td>'+euro(x.amount)+'</td><td><span class="tag '+(x.status==='Erledigt'?'ok':'warn')+'">'+esc(x.status)+'</span></td><td><button onclick="del(\'orders\',\''+x.id+'\')">Löschen</button></td></tr>').join('')||empty(6,'Keine Aufträge.');
$('#invoicesBody').innerHTML=db.invoices.map(x=>'<tr><td>'+esc(x.number)+'</td><td>'+esc(x.customer)+'</td><td>'+esc(x.due)+'</td><td>'+euro(x.amount)+'</td><td><span class="tag '+(x.status==='Bezahlt'?'ok':'danger')+'">'+esc(x.status)+'</span></td><td><button onclick="del(\'invoices\',\''+x.id+'\')">Löschen</button></td></tr>').join('')||empty(6,'Keine Rechnungen.');
$('#itemsBody').innerHTML=db.items.map(x=>'<tr><td>'+esc(x.name)+'</td><td>'+esc(x.category)+'</td><td>'+esc(x.stock)+'</td><td>'+esc(x.unit)+'</td><td>'+euro(x.price)+'</td><td><button onclick="del(\'items\',\''+x.id+'\')">Löschen</button></td></tr>').join('')||empty(6,'Noch keine Items.');
let cash=db.cash.reduce((a,x)=>a+(x.type==='Einnahme'?1:-1)*(+x.amount||0),0);$('#cashTotal').textContent=euro(cash);$('#cashBody').innerHTML=db.cash.map(x=>'<tr><td>'+esc(x.date)+'</td><td>'+esc(x.description)+'</td><td>'+esc(x.type)+'</td><td>'+euro(x.amount)+'</td><td><button onclick="del(\'cash\',\''+x.id+'\')">Löschen</button></td></tr>').join('')||empty(5,'Keine Buchungen.');
$('#appointments').innerHTML=db.appointments.map(x=>'<article class="appointment"><div class="date">'+esc(x.date)+' · '+esc(x.time)+'</div><h3>'+esc(x.title)+'</h3><p class="muted">'+esc(x.person)+'<br>'+esc(x.note)+'</p><button class="btn" onclick="del(\'appointments\',\''+x.id+'\')">Löschen</button></article>').join('')||'<p class="muted">Keine Termine.</p>';
$('#employees').innerHTML=db.employees.map(x=>'<article class="employee"><div class="employee-role">'+esc(x.role)+'</div><h3>'+esc(x.name)+'</h3><p class="muted">'+esc(x.phone)+'<br>'+esc(x.mail)+'</p><button class="btn" onclick="del(\'employees\',\''+x.id+'\')">Löschen</button></article>').join('')||'<p class="muted">Keine Mitarbeiter.</p>';
$('#recipes').innerHTML=db.recipes.map(x=>'<article class="recipe"><div class="employee-role">REZEPT</div><h3>'+esc(x.name)+'</h3><p class="muted"><b>Zutaten:</b><br>'+esc(x.ingredients)+'</p><p class="muted"><b>Ergebnis:</b> '+esc(x.output)+'</p><button class="btn" onclick="del(\'recipes\',\''+x.id+'\')">Löschen</button></article>').join('')||'<p class="muted">Keine Rezepte.</p>';$('#commissionEmployee').innerHTML=db.employees.map(x=>'<option>'+esc(x.name)+'</option>').join('')||'<option>Kein Mitarbeiter</option>'}
const forms={order:['orders','Auftrag',[['customer','Kunde','text'],['order','Bestellung','text'],['date','Termin','date'],['amount','Betrag (€)','number'],['status','Status','select','Offen|In Bearbeitung|Erledigt']]],appointment:['appointments','Termin',[['title','Titel','text'],['person','Person / Kunde','text'],['date','Datum','date'],['time','Uhrzeit','time'],['note','Notiz','textarea']]],invoice:['invoices','Rechnung',[['number','Rechnungsnummer','text'],['customer','Kunde','text'],['due','Fällig am','date'],['amount','Betrag (€)','number'],['status','Status','select','Offen|Bezahlt|Überfällig']]],item:['items','Item / Lagerartikel',[['name','Name','text'],['category','Kategorie','text'],['stock','Bestand','number'],['unit','Einheit','text'],['price','Verkaufspreis (€)','number'],['description','Beschreibung','textarea']]],cash:['cash','Kassenbuchung',[['date','Datum','date'],['description','Beschreibung','text'],['type','Typ','select','Einnahme|Ausgabe'],['amount','Betrag (€)','number']]],employee:['employees','Mitarbeiter',[['name','Name','text'],['role','Position','text'],['phone','Telefon','text'],['mail','E-Mail','email']]],recipe:['recipes','Rezept',[['name','Rezeptname','text'],['ingredients','Zutaten / Mengen','textarea'],['output','Ergebnis / Item','text'],['note','Herstellungshinweis','textarea']]]};
function openForm(k){let [type,title,fields]=forms[k],h='<p class="eyebrow">VERWALTUNG</p><h2>'+title+' anlegen</h2><form onsubmit="submitForm(event,\''+k+'\')"><div class="form-grid">';fields.forEach(([n,l,t,o])=>{h+='<label class="'+(t==='textarea'?'full':'')+'">'+l+(t==='select'?'<select name="'+n+'">'+o.split('|').map(v=>'<option>'+v+'</option>').join('')+'</select>':t==='textarea'?'<textarea name="'+n+'"></textarea>':'<input name="'+n+'" type="'+t+'" required>')+'</label>'});h+='</div><div class="form-actions"><button type="button" class="btn" onclick="closeForm()">Abbrechen</button><button class="btn btn-gold">Speichern</button></div></form>';$('#formContent').innerHTML=h;$('#modal').classList.add('show')}
function closeForm(){$('#modal').classList.remove('show')}function submitForm(e,k){e.preventDefault();let [type]=forms[k],o={id:uid()};new FormData(e.target).forEach((v,n)=>o[n]=v);db[type].push(o);save();closeForm()}function calc(){$('#commissionResult').textContent=euro((+$('#commissionRevenue').value||0)*(+$('#commissionRate').value||0)/100)}$('#commissionRevenue').addEventListener('input',calc);$('#commissionRate').addEventListener('input',calc);$('.menu-toggle').onclick=()=>$('.nav').classList.toggle('open');document.querySelectorAll('.nav a').forEach(a=>a.onclick=()=>$('.nav').classList.remove('open'));render();